### PR TITLE
Not tested.

### PR DESCRIPTION
**Pull request by cthuluhoop123**
some cleanups

### CODE REVIEW

**Comment by YabaiNyan** [comment]
Will review pull request once home. Also please remove the edit on the "on ready" console log. It is appreciated if outputs are kept the same on code cleanup. ☆ミ

**Comment by YabaiNyan** [comment]
Oh and btw test as well if possible thanks

**Comment by cthuluhoop123** [comment]
Sorry. Only losers test their code.

**Comment by YabaiNyan** [comment]
Closing pull request due to improper methodology

**Comment by YabaiNyan** [comment]
Testing when available

**Comment by YabaiNyan** [comment]
Commented on obvious errors, will test once back.

**Comment by YabaiNyan** [comment]
Looks good will test asap then merge

**Comment by YabaiNyan** [comment]
Please edit readme.md to reflect change to dotenv (installation section)

(or I can do it later that works too)

**Comment by YabaiNyan** [comment]
Fixed an assignment error and tested. Merging with main branch

**Pull request merged**
